### ISSUE TITLE
How to use popup in another popup

### ISSUE THREAD

**Issue by chandandas** [ng2-ui/ng2-popup#3]
Hi, 

I have app component, where i have used ng2-popup directive to open a popup using ComponentA. 

Now i need to open another popup called ComponentB from ComponentA. I tried but it replaces ComponentA with ComponentB which does not work in my scenario. 

Ex: I open a popup Employer Component and then i have a button, clicking on it should show list Employees. How can i do this? 

Can anyone help me here!!!

**Comment by allenhwkim** [comment]
Thanks for asking, but this feature is not supported, and I highly do not recommend to open a popup inside a popup.
