### ISSUE TITLE
webpack integration

### ISSUE THREAD

**Issue by jsirney** [ng2-ui/ng2-popup#5]
I am converting my app to use webpack, ng2-popup fails to be resolved. worked fine in systemjs.config.
import { Ng2PopupModule } from 'ng2-popup';  intellisense shows this valid but I get this on the console:
Uncaught SyntaxError {_nativeError: Error: Unexpected value 'Ng2PopupModule' imported by the module 'AppModule'
    at SyntaxError.BaseE…}

**Comment by allenhwkim** [comment]
The recent version. 0.4.0, should be webpack friendly. Please re-install ng2-popup and try again.

**Comment by jsirney** [comment]
Could not get it to upgrade until I put the version 0.4.0 into package.json file. Also had to upgrade ng2-overlay as well.
