### ISSUE TITLE
Parameters passing to popup

### ISSUE THREAD

**Issue by vanamaa** [ng2-ui/ng2-popup#7]
How can we pass parameters to Popup. can you provide an example?

**Comment by allenhwkim** [comment]
@vanamaa thanks for finding this out.
Here you can find example.

https://github.com/ng2-ui/ng2-popup/blob/master/app/app.component.ts#L45

and here how it works
https://github.com/ng2-ui/ng2-popup/blob/master/src/ng2-popup.component.ts#L76

**Comment by allenhwkim** [comment]
On the second thought, For custom popup(a component that you have), I do not see the way to pass parameters to the popup instance except `popupOptions`.

You still can pass it to your component(custom one), if you have property `popupOptions`.

```
@Component({
  template: `
    <p>This is custom popup</p>
    {{number}} <button (click)="number = number+1">increase number</button><br/>
    <button (click)="popup.close()">close</button>
  `
})
export class CustomPopupComponent {
  number: number = 0;
}
```

It may not be prefect for your situation, but let me know if I can
